name: Build the ApiGateway

on:
  push:
    branches:
      - master
      - 'releases/**'
    paths:
      - "ApiGateway/**"
      - ".github/workflows/build-api-gateway.yml"
  pull_request:
    branches: 
      - master
      - dev
    paths:
      - "ApiGateway/**"
      - ".github/workflows/build-api-gateway.yml"

env:
  PROJECT_PATH: 'ApiGateway/ApiGateway.csproj'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Setup docker
      uses: docker/setup-buildx-action@v1

    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
       context: ./
       file: Dockerfile_ApiGateway
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/kwetter_apigateway:latest